### ISSUE TITLE
Screen Garbage is back

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#29]
Well, it seems that, with the latest commit (both Corbenik-UN and Skeith, so it's not an issue with my compilation), the garbage before splash is back. 

If it matters, I'm using arm9loaderhax_si.bin as my arm9loaderhax payload.

There's no garbage if I use non-screeninit a9lh (/arm9loaderhax.bin) .

**Comment by chaoskagami** [comment]
It doesn't affect anything negatively - aside from being annoying. Since reinitializing the screen is mandatory, I suggest using a non-screeninit arm9loaderhax if you don't like this at the moment. This takes a disproportionate amount of effort to fix, so I'm not going to fix it soon. It's minor.

**Comment by chaoskagami** [comment]
Interestingly, it appears some subset of this issue isn't my fault.

AuroraWright's a9lh implementation doesn't properly clear the screen when screeninit mode is used, resulting in garbage/previous state showing for a few moments - and there's nothing I can do about that, because it isn't my fault. This covers the subset when booting screeninit on AuroraWright's a9lh, as well as hitting 'Reboot' in the menu.

**Comment by chaoskagami** [comment]
https://github.com/chaoskagami/corbenik/commit/8e0ebc1b35f04fdea09bf8de4f1f5acdb3ad07d0
