### ISSUE TITLE
Crediting issues

### ISSUE THREAD

**Issue by Mrrraou** [chaoskagami/corbenik#3]
@TiniVi isn't credited for the screen deinit code:
https://github.com/chaoskagami/corbenik/blob/master/source/firm/firm.c#L288-L292
https://github.com/AuroraWright/Luma3DS/wiki/Credits

@TuxSH, @delebile, @AuroraWright, @Steveice10 aren't credited for the Process9/Kernel9 patches, for the loader patches, and for the AGB and TWL patches.
https://gist.github.com/Steveice10/8a6965c59192ac970832
https://github.com/AuroraWright/Luma3DS/blob/developer/source/patches.c#L171-L179

@dark-samus, @b1l1s, @Normmatt, @delebile (and other contributors) aren't credited for figuring out screen init.

@yifanlu's crediting is unclear: @yifanlu made 3ds_injector, which is an opensource replacement for Process9's loader module.

@Reisyukaku, @AuroraWright and @Normmatt aren't credited for the emuNAND/redNAND patches.

**Comment by chaoskagami** [comment]
I was more concerned with getting code working at the moment than crediting everybody in existence. Do you know how ridiculous that would become, and why some projects just don't bother?

No work is completely original. Mankind has based work on others since the stone age.

All the code here is GPLv3, which as a point doesn't require attribution, and documentation is free. I could remove all the attribution if I wanted and it would be a-ok legally. Anyways, this is a suggestion, not a problem.

I credit where my code is directly derived from somebody else's, and people can go look at their credit list if they want to get a more complete list.

To address some of these:

Loader: I thought I was pretty clear about @yifanlu's loader, but evidently not. I'll add a URL to the original git repo when I have time.

Screeninit: Blame Luma for not documenting.

Screen deinit: Blame mid-kid. That was from Cakes' code, which was independently written as far as I know. Also, four lines aren't worth arguing over. That's 32 bytes of 95k.

Patches: TWL/AGB didn't involve Luma's code at all, it was directly based on @Steveice10's paste. I can add headers to all the patches specifying what they're based on, if you want to nitpick, but you're wasting time I could be coding.

EmuNAND: This is based on Cakes (assembly) and Luma (C). Not to mention, the C side has had more than 50% changed, so that's absurd.

**Comment by Mrrraou** [comment]
It's not because some projects don't that all projects shouldn't give credit.
And sure, that is true. But everyone contributed on something, and so, I think it would be nice to credit them.
Blaming Luma for not documenting is ridiculous, though: https://github.com/AuroraWright/Luma3DS/wiki/Credits
And even if the patches are based from @Steveice10's paste, which contains some of @TuxSH's patches and @AuroraWright's patches (for N3DS), they should get credit. And the TWL patches are from @TuxSH and @Steveice10 too.
And I never said Rei invented emuNAND.

Anyway, I don't want you to add headers or anything, but just credit them for the work they have done in the README. Thanks.

**Comment by chaoskagami** [comment]
I understand where you're coming from, at least. I'll edit the credits list when I get the time.

This is just courtesy and not legally required, so I'll go ahead and close this issue.

**Comment by chaoskagami** [comment]
94e8b1c8bed1ea29d600a4acc764a33a0ac5e649 / 6490925b73dcd4e30537e8d8cca395986aac71ca

**Comment by fox8091** [comment]
Just wanted to say, it is legally required. See parts 4 and 5 of the license. Maybe read it before using it? :)

**Comment by chaoskagami** [comment]
That actually depends on whether the author has externally said he wants credit by name (which triggers section 7, part b.)

Otherwise, it doesn't count as a 'Verbatim Copy' (4) and therefore is only required to carry a 'Prominent Notice', e.g. the README and Help menu as section (5) states (4) should be interpreted. Otherwise, the license is intact and I'm crediting direct code use that I'm aware of for the projects.

Information originating from 3DBrew, other people's RE work, etc aren't covered by the GPL if I'm not using their code. The GPL only covers code and binaries.

I do try to credit though. Everybody does awesome work and the last thing I want to do is piss anyone off. ;P
