### ISSUE TITLE
Replacing TwlBg.cxi

### ISSUE THREAD

**Issue by leo60228** [chaoskagami/corbenik#33]
I'm probably being stupid here, but how do I do this?

**Comment by chaoskagami** [comment]
You don't yet.

I only have infrastructure in place for native_firm system modules right now, but this development (while admittedly kind of useless atm) put me in a bit of a scramble to fix this up ASAP.

**Comment by leo60228** [comment]
Thanks!

**Comment by chaoskagami** [comment]
Fixed by https://github.com/chaoskagami/corbenik/commit/f992ea778b1cb0bb22c7939ec5b8ac27959c7b97

I'd still rather get some infrastructure to patch individual system modules. Either way, you can drop twlBg.cxi in /corbenik/lib/modules/twl/twlBg.cxi and it'll pick it up now. _shrugs_

NitroHax was tested and works, anyways.
