### ISSUE TITLE
[Enhancement]Auto-remove config if said config is not compatible with current CFW

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#37]
Something like Luma's, where if the config format changes, Corbenik/Skeith will know the config is older, and delete it, forcing the user to make a new one. I'd say that's a pretty cool feature.

**Comment by chaoskagami** [comment]
1) Corbenik regenerates the config automatically if it detects that any part is malformed.

2) If the version of the config doesn't match the version of corbenik, it automatically deletes the configuration file. I bump the version whenever I change something in an incompatible way.

3) Some values are automatically patched if they are invalid so long as checks 1 and 2 pass.

Furthermore, 1+2 have been in corbenik since the very first release.

If what you're asking is if I will make an effort to correct old config data once wip/plainconf (more like wip/badtime, heh) is merged, the answer is that I'll be autodeleting configuration if I detect it.

Closing, RTFS, etc.

**Comment by gnmmarechal** [comment]
Oh, hadnt noticed it did that already. Lol
