### ISSUE TITLE
Booting from CTRNAND (like Luma)

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#44]
Just an idea for an enhancement. It's not something I particularly care about using that much, it's not very important, and I've no idea what is needed for this to happen, but hey, it'd be an enhancement, so I've decided to post it here.

**Comment by chaoskagami** [comment]
This is a pain in the ass for multiple reasons. As much as I'd love to do that, it's out of scope right now. To list immediate things:

1) This requires loader to be granted NAND r/w permissions. Not a huge annoyance, but something to think about.
2) There's a lot of small moving parts like patches, config, etc. Which device should they be loaded off if both are present? Should both be treated as storage devices? Where is configuration data loaded from?

Aside from this, there's multiple blockers preventing any actual work on the core. I'm unable to update libctr9 due to recent changes being incompatible with my infrastructure (FatFs no longer exposed directly, forcing use of crt0, requiring the use of libsysbase heap - ~~and this not working for some reason.~~ Fixed, ha) Aside from that, there's so many architectural problems in corbenik itself that are unfixable short of a complete rewrite.

I'm sort-of-working on that "rewrite", but all I've achieved so far is porting the VM to be a generic program and started work on platform glue to abstract things. That said, I'm on valve time, and HL3 will probably come out before I'm anywhere close to done.

**Comment by NinjaBoyLao** [comment]
What does that mean, that the rewrite won't be here anytime soon? (Like, will updates be difficult, few and far between, or will we just need to wait) I was under the impression corbenik worked fine, so I don't understand why it would need one for anything other than the suggestion this issue is about.

**Comment by chaoskagami** [comment]
I suppose it isn't relevant to this issue in general. Apologies, you're right.

Background: While corbenik does work fine for actual use -- the code has design issues in API and architecture. It's not actual bugs or misbehavior to be clear, but a lack of generic interfaces and clear component separation has lead to the current codebase being difficult to extend and a mess of cross-dependencies between source files.

Back to this issue, however: this is very annoying to fix with how corbenik is designed. In near every part of the code (including loader) it not only requires, but assumes an SD card is present. I *have* however gotten newlib/libsysbase malloc to work since that post eight days ago, so things are looking a bit less like the rewrite is even needed now.

**Comment by chaoskagami** [comment]
Closing for now; I may reopen at a future date.
