### ISSUE TITLE
Data abort after first time configuration

### ISSUE THREAD

**Issue by sykhro** [chaoskagami/corbenik#61]
As title states, this only happens on the very first boot attempt (or rather, the first time firm is decrypted); haven't really looked into possible causes

EUR New3DS
Boot log:
[boot.txt](https://github.com/chaoskagami/corbenik/files/785204/boot.txt)

**Comment by NinjaBoyLao** [comment]
oh boy im getting this too on the official skeith build. i think the last time this happened i had to copy over some decrypted stuff from my last working corbenik installation (which stopped working after 11.3)

**Comment by NinjaBoyLao** [comment]
yeah this is what you gotta do if you at least had a working corbenik install before: go to /corbenik/var/cache/ and copy "p_native" to the exact same location inside /skeith

**Comment by sykhro** [comment]
I know how to make it work. It only fails after the decryption of firm.

**Comment by chaoskagami** [comment]
Looks like I made a slight boo-boo in fixing the whole memory corruption thing. In summary, what I *think* is happening:

 * CDN NCCH is decrypted via extract_firm_from_ncch and assigned to firm
 * extract_firm_from_nccch does not memmove the firm to the beginning of the buffer we already have, it allocates a new one sized to match the firm image
 * Injection of modules then clobbers memory after the FIRM due to lack of space (likely leading to our abort)

I'm aware this renders region patches ineffective, but if turning module injection off results in successful boot (albeit sans loader), it would certainly confirm this.

**Comment by chaoskagami** [comment]
Whenever the next nightly gets built by jenkins (or if you build it yourself) that commit should fix the issue.

**Comment by NinjaBoyLao** [comment]
Will report back when i've tested another clean install

**Comment by NinjaBoyLao** [comment]
yup, works perfectly now
