### ISSUE TITLE
Enabling Firmlaunch Hook breaks TWL_FIRM on EUR N3DS

### ISSUE THREAD

**Issue by qwertyatom100** [chaoskagami/corbenik#65]
I'm not sure why, as the system still boots and everything seems to work. However, when I go to launch a legit DS cartridge (New Super Mario Bros) it just blackscreens, but the game works without the option enabled so I don't know what the problem is. I don't know if logs would be helpful because the issue occurs after boot is completed but if you need the logs I will upload. TWL patches don't have to be enabled to reproduce. Interestingly, if I enable TWL patches, the system appears to apply the O3DS patches. Maybe there is something different about my specific console? I really don't know and I am hoping you can help.
If you need anything else feel free to ask.

**Comment by gnmmarechal** [comment]
Are you on 11.3?

**Comment by qwertyatom100** [comment]
No, I am using an 11.2 EmuNAND with an 11.2 SysNAND if that matters as well.

**Comment by GrayJack** [comment]
I wonder if it's related with my problem, I have a 11.2 SysNAND and I'm having problems with TWL_FIRM as well, even with the sha256 hash being the same as others

**Comment by chaoskagami** [comment]
@qwertyatom100, are you still having issues regarding this?

**Comment by qwertyatom100** [comment]
Yes I am

**Comment by chaoskagami** [comment]
I'm sure you know this already, but in the readme, I request uploading logs. If you could do so, I would very much appreciate it.

Additionally, I'd like to know what release you've installed from, as well as _how_ you installed it, since only manual installation is supported (and @gnmmarechal's updater has known issues.)

Additionally, have you tried basic debugging steps, such as checking sha512sums and doing a completely clean reinstall?

Has your sysNAND been modified in any way, such as modifying whitelists or TWL_FIRM?

It's entirely possible this is related to emuNAND somehow, but I'd prefer to rule everything else out first, especially since I'm unable to reproduce this.

**Comment by NinjaBoyLao** [comment]
@chaoskagami you're so polite and patient. I browse through things aimlessly on this repo just sort of hoping to eventually understand even half the stuff you do here. and like.. props to you man, i would've lost my shit months ago.

**Comment by gnmmarechal** [comment]
yep, especially the fresh installation feature, which I *still* haven't looked at to fix x.x

I'll probably eventually rewrite everything.... again.

**Comment by qwertyatom100** [comment]
Apparently my email has crapped out on me and I didn't get any notification about replies. I'm really sorry about that and thank you for your patience.
I am as of right now unable to debug this issue as I have switched to boot9strap, and you have mentioned TWL_FIRM currently not working anyway.
I have also cleaned my SD card, and can't upload old logs.
I'll close this for now as it currently doesn't apply to me.
I'll open it in future if the issue applies when boot9strap support is completed.
Thanks everyone!
