### ISSUE TITLE
HBL access for o3DS CFW users on 11.4

### ISSUE THREAD

**Issue by NinjaBoyLao** [chaoskagami/corbenik#70]
Apparently, if you use the 11.2 payload, and you're using Luma and 11.4, you can still get into the HBL, for some reason. This is above my tier, but is this functionality available in corbenik? I have carefully dug through all of your posted information and haven't managed to find anything, although I may well have missed it. I'll close this asap once I hear from you.

**Comment by chaoskagami** [comment]
Short answer: yes, it works. And it should work with zero fudging around via the loader, including autofetching an 11.4 payload.

Long answer: I never did add the patch to re-enable gspwn, but smealum and co. made the payloads not require this. Therefore, as long as the latest HBL payloads are used, it should function perfectly fine with no additional work. You should not need to use 11.2 payloads.

Since smea and co fixed the issue with the payloads, I'm not planning to implement the gspwn fix anytime soon, since it's a security hole in the OS and no longer needed nor relevant. Homebrew should not mean running an insecure system.

Closing.

**Comment by NinjaBoyLao** [comment]
I'm on an o3DS and the regular 11.4 payloads don't work. The 11.2 ones, however, work for some reason, but only with luma. 11.4 payloads will error out with corbenik and luma. 11.2 payloads disguised as 11.4 ones by renaming will seem to work but then crash to the HOME menu on corbenik.  

My bad on not specifying my system, I meant to.

**Comment by chaoskagami** [comment]
https://twitter.com/smealum/status/864931219074539520

Again, 10.2 payloads work because Luma patches out the GSP checks.
