### ISSUE TITLE
Sleuth bricked my 3ds!! NOT HAPPY chaoskagami!

### ISSUE THREAD

**Issue by ToadillerYT** [chaoskagami/corbenik#76]
I tried to use the firm and cetk from Corbenik for skeith. Now Luma3DS is broken and when I launch any app it says to download again from the eshop and system settings always crashes and I lost my NAND backup when my computer got a virus! Now what genius?!?

**Comment by gnmmarechal** [comment]
Shut up. Corbenik is not intended for those who don't have the knowledge to use it. Your fault. Corbenik is provided without any warranty. Not to mention, it's no longer in active development. Take your complaints somewhere else.

**Comment by Dionicio3** [comment]
Another way you went wrong: not having multiple NAND backups on an online cloud, always make a backup of the NAND somewhere like Google drive or OneDrive

**Comment by gnmmarechal** [comment]
I make a NAND backup everytime I make changes to my NAND, so I have quite a few. In different drives and all, of course.

**Comment by zoogie** [comment]
Software darwinism at play here.

**Comment by chaoskagami** [comment]
Okay, I was torn on whether to reply to this darwin-award "issue" report or just attach PEBKAC, close and be done with it, but y'know what, I laughed.

So:
 * Your inability to follow clearly explained directions in the README is not my fault.
 * Your installation of malware from "cool shoftware" sites or drive-by-exploits on pornhub is not my fault.
 * Your subsequent lack of NAND dumps is not my fault.
 * This isn't even a bug report.
 * This isn't a forum. Save the dumbassery for gbatemp.

I'm not really obligated to help you at all, "genius," especially since I've washed my hands of CFW, but since I'm feeling kind today...there's zero way corbenik could cause this issue.

The only thing that can cause every title simultaneously to stop launching is deleting all of your tickets or restoring someone else's tickets afaik. CFW doesn't touch this so whatever you did, you were the only one responsible for shooting yourself in the foot.

**Comment by Derek1199** [comment]
@ToadillerYT the only way you could brick your 3DS Is if you were dumb enough to turn off firm protection, then update your 3DS on sysnand. Seriously just use luma. Its noob-friendly corbenik is intended for "advanced users, not newbies". If you don't know how to use corbenik, then don't use it.

**Comment by ToadillerYT** [comment]
Never mind. I was able to put it on a disc. Is it fixable and please don't put Harte comment me..

**Comment by ToadillerYT** [comment]
Stupid autocorrect.. I meant to put hate instead of Harte.
